---
all:
  vars:
    ansible_user: isucon
    ansible_ssh_private_key_file: ~/.ssh/isucon13-sontaku_id
  hosts:
    is1:
      ansible_host: 52.195.55.156
    is2:
      ansible_host: 52.196.253.157
    is3:
      ansible_host: 13.230.50.204
