---
- name: Install New Relic infrastructure and logs
  hosts: all
  roles:
    - role: newrelic.newrelic_install
  vars:
    targets:
      - infrastructure
      - logs
      - mysql
      - nginx
  environment:
    NEW_RELIC_API_KEY: NRAK-????????
    NEW_RELIC_ACCOUNT_ID: 2454034
    NEW_RELIC_REGION: US
    NEW_RELIC_MYSQL_ROOT_PASSWORD: root
    NEW_RELIC_MYSQL_PASSWORD: isucon
    NEW_RELIC_MYSQL_USERNAME: isucon